---
language: objective-c
osx_image: xcode7
xcode_project: xcodeProject/xSwift.xcodeproj
xcode_scheme: xSwiftTests
script:
- xcodebuild test -project 'xcodeProject/xSwift.xcodeproj' -scheme 'xSwiftTests' -sdk
  macosx10.11
- bin/fetch-configlet
- bin/configlet .
